config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update] 
  resources :users, only: [:show] do
    member do
      get :favorites
    end
  end
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :favorites, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }

  before_validation { email.downcase! }

  has_secure_password

  mount_uploader :image, ImageUploader

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless  current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        ContactMailer.contact_mail(@picture.user).deliver
        redirect_to pictures_path, notice: "投稿が完了しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
    if current_user != @picture.user
      redirect_to pictures_path
    end
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to  pictures_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    if current_user != @picture.user
       redirect_to pictures_path
    else
      @picture.destroy
      redirect_to pictures_path, notice: "投稿を削除しました！"
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウト完了'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
      
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites = @user.favorite_pictures
  end

  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_pictures
  end
  
  def edit
    @user = User.find(params[:id])
    if current_user != @user.id
      redirect_to pictures_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを編集しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif  action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <% if logged_in? %>
          <ul class="row">
            <li class="col-md-3"><%= link_to "Picture_app", pictures_path %></li>
            <li class="col-md-3"><%= link_to "Newpost", new_picture_path %></li>
            <li class="col-md-3"><%= link_to "Profile", user_path(current_user.id) %></li>
            <li class="col-md-3"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          </ul>
        <% else %>
          <ul class="row">
            <li class="col-md-4"><%= link_to "Picture_app", pictures_path %></li>
            <li class="col-md-4"><%= link_to "Sign up", new_user_path %></li>
            <li class="col-md-4"><%= link_to "Login", new_session_path %></li>
          </ul>
        <% end %>
      </header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
      <footer>
        <p>chihiro-kakizaki</p>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
        <ul>

        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="picture_content">
      <div class="past_image">
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      </div>
      <div class="new_image">
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      </div>
      <div class="picture_text">
        <%= form.label :投稿内容 %>
        <%= form.text_field :content %>
      </div>
      <div class="picture_submit">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  <%= link_to "投稿一覧", pictures_path,class:"btn_top btn btn-secondary btn-sm" %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>

  <br><%= form.submit  "登録する" %></br>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>


app/views/pictures/edit.html.erb
<div class="post_edit">
  <h2>投稿編集</h2>
  <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<h2>投稿一覧</h2>
<div class="pictures">
  <% @pictures.reverse_each do |picture| %>
    <div class="main">
      <%= picture.user.name %>
      <%= l picture.created_at %>
      <br>
        <%= picture.content %>
      </br>
      <div class="image">
        <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
      </div>
      <div class="btn_menu">
        <%= link_to '詳細', picture_path(picture.id), class:"show btn btn-secondary btn-sm" %>
        <% if picture.user == current_user %>
          <%= link_to "編集", edit_picture_path(picture.id),class:"edit btn btn-secondary btn-sm" %>
          <%= link_to "削除", picture_path(picture.id), method: :delete ,class:"edit btn btn-secondary btn-sm" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
  <h2>新規投稿</h2>

  <%= render 'form' %>

app/views/pictures/show.html.erb
<div class="picture_show">
  <h2>投稿詳細</h2>
  <div class="show_content">
    <%= @picture.content %>
  </div>
  <div class="show_image">
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  </div>

  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="profile_edit">  
  <h2>プロフィール編集</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>  
    <div class="name">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="email">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="password">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="password_confirmation">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="image">
      <%= f.label :プロフィール写真 %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="submit">
      <%= f.submit "Edit my account" %>
    </div>
  <% end %>
</div>
<%= link_to "プロフィールへ戻る", user_path(current_user.id),class:"back btn btn-secondary btn-sm"%>

app/views/users/favorites.html.erb
<div class="favorite_page">
  <h2><%= current_user.name %>お気に入り一覧</h2>

  <div class="favorites">
    <% @favorites.reverse_each do |list| %> 
      <%= image_tag(list.image.url)  %>
    <% end %>
  </div>
</div>

<%= link_to "プロフィールへ戻る", user_path(current_user.id),class:"back btn btn-secondary btn-sm"%>

app/views/users/new.html.erb
<h1>プロフィール登録画面</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :user_image %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>


  

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="mypage">  
  <h2>MyPage:<%= @user.name %></h2>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <p>メールアドレス: <%= @user.email %></p>
  <% if current_user == @user %>
  <%= link_to "プロフィール編集", edit_user_path(current_user.id),class:"edit btn btn-secondary btn-sm" %>
  <% end %>
  <%= link_to "お気に入り一覧", favorites_user_path(current_user.id),class:"favorites btn btn-secondary btn-sm" %>
  <%= link_to "投稿一覧", pictures_path,class:"top btn btn-secondary btn-sm" %>
</div>

